    % ============> CORRECTION FUNCTION <=============================
    % FUNCTION TO DETERMININE THE CORRECTED SEQUENCE BASED ON THE CORRECT
    % PATH GENERATED BY VITERBI ALGORITHM
    
    function corrected=corrector(correctpath)
        global td;
        k=2;
        time=0;
        corrected=[0,0];
        while k< size(correctpath,2)+1
            i=correctpath(k);
            if k == size(correctpath,2)

                o=binarify(td(i+1,time+1,3));
                o=o(2:end);
                corrected=[corrected,o];
                corrected=corrected(3:end);
                return
            end

            if td(i+1,time+1,1)==correctpath(k+1)

               o=binarify(td(i+1,time+1,3));
               o=o(2:end);
               corrected=[corrected,o];
            end

            if td(i+1,time+1,2)==correctpath(k+1)

                o=binarify(td(i+1,time+1,4));
                o=o(2:end);
                corrected=[corrected,o];
            end 
            k=k+1;
            time=time+1;

        end
   
    end